namespace Torifune.Core.Models;

/// <summary>yt-dlp が返す 1 フォーマット(映像/音声/複合)の情報。</summary>
public sealed record FormatInfo(
    string FormatId,
    string? Ext,
    string? VCodec,
    string? ACodec,
    int? Width,
    int? Height,
    double? Fps,
    long? Filesize,
    long? FilesizeApprox,
    double? Tbr,
    double? Abr,
    string? FormatNote,
    string? Language,
    string? Protocol)
{
    /// <summary>映像ストリームを含むか。</summary>
    public bool HasVideo => VCodec is not (null or "none");

    /// <summary>音声ストリームを含むか。</summary>
    public bool HasAudio => ACodec is not (null or "none");
}

/// <summary>利用可能な字幕トラック。</summary>
public sealed record SubtitleInfo(string Language, string? Name, bool IsAutoGenerated);

/// <summary>プレイリスト内の 1 エントリ(flat-playlist による軽量情報)。</summary>
public sealed record PlaylistEntry(string? Id, string Url, string? Title, TimeSpan? Duration);

/// <summary>URL 解析結果。単一動画またはプレイリスト。</summary>
public sealed record MediaInfo
{
    public required string Url { get; init; }
    public string? Id { get; init; }
    public string? Title { get; init; }
    public TimeSpan? Duration { get; init; }
    public string? ThumbnailUrl { get; init; }
    public string? Uploader { get; init; }
    public string? Extractor { get; init; }

    /// <summary>プレイリストかどうか。</summary>
    public bool IsPlaylist { get; init; }

    /// <summary>プレイリスト時のエントリ一覧(単一動画では空)。</summary>
    public IReadOnlyList<PlaylistEntry> Entries { get; init; } = [];

    /// <summary>選択可能なフォーマット一覧(単一動画のみ)。</summary>
    public IReadOnlyList<FormatInfo> Formats { get; init; } = [];

    /// <summary>利用可能な字幕一覧。</summary>
    public IReadOnlyList<SubtitleInfo> Subtitles { get; init; } = [];
}
